### ISSUE TITLE
[HIGH][BUG][React] Using headers in api_url.js doesn't refresh with token new value

### ISSUE THREAD

**Issue by fabdarice** [Simba-Market/SimbaFrontEnd#32] opened 2017-09-22 06:38 UTC
Ask Fab

**Comment by fabdarice** [comment] 2017-09-25 05:36
Use getUserProfile function to test

**Comment by RudthMael** [comment] 2017-09-26 06:50
Can't reproduce. Possibly resolved with https://github.com/Simba-Market/SimbaFrontEnd/pull/39

**Closed by RudthMael** 2017-09-26 06:50 UTC
